[package]
name = "examples_market"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
ig-client = { workspace = true }
lightstreamer-rs = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }