[package]
name = "examples_trade"
version = "0.1.0"
edition = "2024"

[dependencies]
ig-client = { workspace = true }
lightstreamer-rs = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }